# Generated by Django 6.0.3 on 2026-04-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='offers/banner/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
