# Generated by Django 6.0.3 on 2026-05-04 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 4, 9, 29, 52, 745049, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 4, 9, 30, 5, 518559, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
