# Generated by Django 6.0.4 on 2026-05-05 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_offer_menu_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='menu.menuitem'),
        ),
    ]
