# Generated by Django 6.0.3 on 2026-05-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_offer_menu_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
