# Generated by Django 6.0.4 on 2026-06-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_alter_menuitem_price_alter_offer_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
