# Generated by Django 6.0.4 on 2026-06-15 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_footer_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
    ]
