# Generated by Django 6.0.3 on 2026-06-12 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_table_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='dish_names',
            new_name='item_names',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='dish_name',
            new_name='item_name',
        ),
    ]
